### ISSUE TITLE
core_ext/select_manager.rb uncompatible with Arel::SelectManager

### ISSUE THREAD

**Issue by shooma** [SAP/activerecord-hana-adapter#11]
Query like `PGBasedModel.select('count(*)')` raise error
```
NameError: uninitialized constant Arel::SelectManager::SqlLiteral
	from /home/shooma/.rvm/gems/ruby-2.4.2@tps/bundler/gems/activerecord-hana-adapter-29356cbb2646/lib/arel/core_ext/select_manager.rb:13:in `block in project'
	from /home/shooma/.rvm/gems/ruby-2.4.2@tps/bundler/gems/activerecord-hana-adapter-29356cbb2646/lib/arel/core_ext/select_manager.rb:7:in `map'
	from /home/shooma/.rvm/gems/ruby-2.4.2@tps/bundler/gems/activerecord-hana-adapter-29356cbb2646/lib/arel/core_ext/select_manager.rb:7:in `project'
```

`Nodes::SqlLiteral.new` should be used instead of `SqlLiteral.new`

**Comment by shooma** [comment]
issue fixed for me
